name: Model-Training
on: 
  workflow_dispatch:
    inputs:
      credential:
          description: 'clearml training feeder credential'     
          required: true
          default: 'api { 
              # Richardles Workspace
              web_server: https://app.clear.ml
              api_server: https://api.clear.ml
              files_server: https://files.clear.ml
              credentials {
                  "access_key" = "Y26LJVWNURD8DZZTGK39"
                  "secret_key" = "sbuXwW6uYWiX8XydT73EDh4Yayn3ZpO8FdjDZ3BJmoInQJNLYo"
              }
          }'
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          clearml-init
          api { 
              # Richardles Workspace
              web_server: https://app.clear.ml
              api_server: https://api.clear.ml
              files_server: https://files.clear.ml
              credentials {
                  "access_key" = "Y26LJVWNURD8DZZTGK39"
                  "secret_key" = "sbuXwW6uYWiX8XydT73EDh4Yayn3ZpO8FdjDZ3BJmoInQJNLYo"
              }
          }
          # echo "${{ github.event.inputs.credential }}"
          python train_keras_lstm.py
        # shell: bash
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results.txt >> report.md
          cml send-comment report.md
